# Generated by Django 4.2.4 on 2023-08-04 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_customuser_is_superuser"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={"verbose_name": "User", "verbose_name_plural": "Users"},
        ),
        migrations.AlterModelTable(name="customuser", table="User",),
    ]
