# Generated by Django 4.2.4 on 2023-08-04 19:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0004_customuser_groups_customuser_user_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="create_at",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="customuser",
            name="update_at",
            field=models.DateField(auto_now=True),
        ),
    ]
